python run_e3c_double.py \
	--env-id SuperMarioBros-v2 \
	--use-cuda \
	--use-gae \
	--life-done \
	--single-stage \
	--training \
	--standardization \
	--num-worker 16 \
	--sample-size 8 \
	--beta 0.95 \
	--name e3c_b95
